name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.13.x", "1.14.x", "1.15.x", "1.16.x", "1.17.x" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Run gofmt
      run: diff -u <(echo -n) <(gofmt -d .)

    - name: Test
      run: go test -timeout 10m -v -race ./

    - name: Run go vet
      run: go vet ./